name = "alook-ws-do"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 0.1

[observability.logs]
invocation_logs = true
head_sampling_rate = 0.1
destinations = ["grafana-logs"]

[observability.traces]
enabled = true
head_sampling_rate = 0.05
destinations = ["grafana-traces"]

[dev]
port = 8789
inspector_port = 9230

[[d1_databases]]
binding = "DB"
database_id = "1593b87c-d8a8-4cdf-b6c0-c80d94442654"
database_name = "alook-app"

[[durable_objects.bindings]]
name = "WS_DO"
class_name = "WebSocketDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketDurableObject"]
